### ISSUE TITLE
[Github][Webhook] Event 및 Post body 내용 정리 후 정책 결정

### ISSUE THREAD

**Issue by yunsangr** [linewalks/be-common#10]
## 내용
현재 너무 많은 이벤트에 많은 내용들이 중복되는 내용과 함께 구글챗에 출력이되고 있다.  필요한 이벤트와 필요한 내용들만 중복없이 구글챗에서 출력되도록 합니다.

## 현재 깃헙에서 구글챗으로 가는 알림 이벤트
- 아래와 같은 형식으로 정리하였습니다.
```
- 구글 알림이 가는 이벤트 주제
  - 기존 이벤트: 해당 주제 관련해서 현 시점 알림이가는 모든 이벤트들
  - 필요한 이벤트: 필요하다고 판단되는 이벤트들
  - 전달 정보: 필요한 이벤트들이 구글챗으로 전달하게될 최소 정보
```
- 같은 이벤트 주제들은 하나의 쓰레드에서 알림을 전달하게 구현

### Issue
 - `Issue`
   - 기존 이벤트: opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned, locked, or unlocked.
   - 필요한 이벤트: opened, edited, deleted, closed, reopened, assigned, labeled, milestoned
   - 전달 정보
       - `opened`: 이슈 생성자, 이슈 제목(이슈 링크)
           - ex) `yunsangr`님이 `이슈 제목` 이슈를 `생성`하였습니다.
       -  `edited`, `deleted`, `closed`, `reopened`, `assigned`, `labeled`, `milestoned`: 행위자, 행위 + 이슈링크
           - ex) `yunsangr`님이 이슈를 `종료`하였습니다.
- `Issue comment`
   - 기존 이벤트: created, edited, or deleted.
   - 필요한 이벤트: created
   - 전달 정보
      - `created`: 이슈 댓글 작성자, 댓글 링크 (내용 생략)
          - ex) `yunsangr`님이 댓글을 `생성`하였습니다. 

      
### PR
- `Pull request`
  - 기존 이벤트: opened, closed, reopened, edited, assigned, unassigned, review requested, review request removed, labeled, unlabeled, synchronized, ready for review, converted to draft, locked, unlocked, auto merge enabled, auto merge disabled, milestoned, or demilestoned.
   - 필요한 이벤트: opened, closed, reopened, review requested
   - 전달 정보
       - `opened`: PR 생성자, PR 제목(링크)
          - ex) `yunsangr`님이 `PR 제목` 풀리퀘스트를 `생성`하였습니다.
       - `closed`, `reopened`: 행위자, 행위, PR링크
          - ex) `yunsangr` 님이 풀리퀘스트 `종료`하였습니다.
 - `Pull request review comment`
   - 기존 이벤트: created, edited, or deleted
   - `Pull request review` 단계에서 리뷰 사항을 댓글로 남기고 리뷰 제출을 하기때문에 댓글 마다 매 번 알림이 가야될 필요는 없는것 같아 제거.
  
 - `Pull request review` 
   - 기존 이벤트: submitted, edited, or dismissed
   - 필요한 이벤트: 그대로
   - 전달 정보
      - 행위자, 행위, 해당 링크
         - ex) `yunsangr`님이 리뷰를 `제출`하였습니다. 
         - ex) `yunsangr`님이 리뷰를 `종료`하였습니다. 
 

### Commit comments
- Commit or diff commented on.
  - PR 리뷰를 하기때문에 커밋 리뷰를 따로 하지는 않기때문에 해당 이벤트는 제거.
  
 
### 이벤트 주제 별 구현 상항
- [x] issue
- [x] Issue comments
- [x] PR
- [x] PR review

### 프로젝트별 적용 상황

- [x] CLUE-Client
- [x] CLUE-API

  
## 참고링크
- [깃헙 웹훅 이벤트별 정보](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads)
- [깃헙 웹훅 관리 젠킨스 폴더](http://192.168.0.21:8888/job/Github%20Webhook%20Manager/)

**Comment by westhyena** [comment]
### Issue
* 추가
  * assigned: 업무가 누구한테 할당되었는지 알려주면 좋겠음
  * labeled: 레이블 설정에 따라 필요할 수도 있겠다. 작업 진행 상황을 Label로도 표시해줄 수 있음
  * milestoned: 마일스톤이 변경되어 예정된 일정보다 늦어지고 있는지 상황을 알 수 있음

### PR
* `Pull request`
  * 추가
    * review requested: 리뷰 요청 받은 것 바로 알 수 있음
