### ISSUE TITLE
[Kubernetes] KONG 적용

### ISSUE THREAD

**Issue by yunsangr** [linewalks/be-common#39]
### 내용
KONG ingress controller 를 minikube 에 적용하여 nginx 를 대체하는 Gateway 구축을 진행합니다.
#38 내용을 참고합니다.

![image](https://user-images.githubusercontent.com/48658642/141393569-11c4907a-dbb1-45ed-969e-9301a0545781.png)

- Kong 의 리소스들은 k8s의 리소스로 등록되어 사용
- API gateway 는 Ingress로 등록
- Plugin 들은 CRD(Kubernetes Custom Resource Definition)으로 등록
- k8s API server -> Kong Ingress Controller -> Kong DB/Memory -> Kong Proxy (Gateway)
- Kong - k8s 리소스 맵핑을 설명한 그림
![image](https://user-images.githubusercontent.com/48658642/141389975-a1a0fba3-c214-423c-b394-e1a8bb85bad0.png)
- DB-less 모드로 설치 권장: 모든 설정이 k8s 컨트롤플래인에 저장되고 DB 관리 걱정이 없어 간편하기 때문
- Ingress in k8s -> Route in Kong : defines a set of rules for proxying traffic.

### Links
- [Kong on Kubernetes (조대협)](https://bcho.tistory.com/1364)
- [Kong Ingress on Minikube Permalink](https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/deployment/minikube/)

**Comment by yunsangr** [comment]
### [Kubernetes Ingress Controller Deployment](https://docs.konghq.com/kubernetes-ingress-controller/2.0.x/concepts/deployment/)
#### Resources
- Namespace (optional): 클러스터의 모든 네임스페이스를 대상으로 프로싱을 하려고하는 경우, 네임스페이스를 `kong` 로 명시해주는게 권장된다.
- Custom Resource (required): Kong 과 Kubernetes 의 자원을 연결하는데 사용되는 Resource 로써 프록싱 행동을 제어하는데 명확한 API를 제공한다.
- RBAC(Role-based access control) permissions (required):  KIC 는 자동적으로 서비스의 팟들을 로드 밸런싱 목적으로 Kubernetes API-server 와 소통하고 동적으로 Kong 설정을 진행합니다. 이를 위해서 RBAC 권한을 사용해 쿠버네티스 자원에 접근이 가능해야합니다.
- Ingress Controller deployment (required): 쿠버네티스에서 Kong 은 Ingress deployment 로써 배포되며 실질적으로 Kubernetes Ingress Controller 역할을 합니다.
- Kong Proxy service (required):  Kubernetes Ingress Controller 가 배포될시에, Kubernetes cluster 외부로부터 traffic 을 받기아 Kong 에게 전달할 수 있게 반드시하나의 service 가 Kong 을 노출하여합니다. 이 노출된 service 를 `kong-proxy` 라고하며 보통 `LoadBalancer` 의 역할을 합니다. 이 `kong-proxy` 를 사용해서 모든 domain 의 DNS records 를 설정하여야 합니다.
- Database deployment and migration(optional): Kubernetes Ingress Controller 는 선택적으로 database 작동할수 있습니다. 만약 database 와 함께 배포된다면 다음에 resources 들이 필요합니다.
  -`StatefulSet`: Kong 의 환경설정을 저장하는 `Postgresql pod` 을 `PersistenceVolume` 와 함께 실행합니다.
  - `internal Service`: `Postgresql pod` 을 위한 `Service` 로써 Kubernetes cluster 환경 내부에서 DNS 를 사용해 Kong 이 Postgresql instance 을 찾을 수 있게합니다.
  - `batch Job`: to run shcema migrations.

#### Deployment options

다음은 상황에 따른 Kubernetes Ingress Controller 를 배포시에 있는 options 들입니다.
- Kubernetes Service Types
  - 배포가 되고나서 적어도 하나의 `Service` 를 사용해 Ingress Controller 를 외부로 부터 노출시켜야합니다.
  - Kubernetes cluster 가  Load Balancers 가 제공되는 cloud 환경에서 동작하면 `Load Balancer`를, 아니라면 `Node-Port` 를 선택하는걸 권장합니다. 
- Database 
  - Kong 을 DB/DB-less 중 어느 모드로 사용할지 선택합니다.

**Comment by jindex2411** [comment]
DB-less 모드 사용시 동적인 적용 및 konga 사용이 불가능 해지네요 ㅠㅠ
우리가 원하던 편리한 사용을 위해서는 DB 모드를 사용해야 될 것 같습니다.

**Comment by yunsangr** [comment]
## Install Kong with Helm

Kong 을 쿠버네티스에 설정하기에는 다양한 상태를 전부 정의해주어햐 하기때문에 난이도가 상당히 높다.
이를 위해 Helm 사용해서 원하는 설정들을 커스텀하면서 설치를 진행하도록 합니다.


#### Helm 란

Pip for Python, Npm for Node 처럼 쿠버네티스를 위한 패키지 매니저이다. 쿠버네티스에서 다양한 기능들을 Helm 을 통해 패키지(Chart)를 다운받아 원하는 값들을 설정해서 사용가능하다.

#### Helm Chart 란

주로 말하는 패키지와 비슷한 개념으로써 쿠버네티스에 적용하기 위해 사용되는 yml 파일들을 특정 형식에 맞추어서 생서된 파일들의 구성이다.

#### Install Kong/Konga

```sh

kong chart 를 원하는 설정값과 함께 구축.
>  helm install my-release kong/kong --set ingressController.installCRDs=false --set postgresql.enabled=true --set admin.enabled=true --set admin.http.enabled=true --set admin.tls.enabled=true --set env.database=postgres --set env.pg_database=kong --set env.pg_user=kong --set pg_password=kong --set postgresql.postgresqlUsername=kong --set postgresql.postgresqlDatabase=kong --set postgresql.postgresqlPassword=kong
konga chart를 로컬에 받아 경로는 ./ 로 주어서 실행.
>  helm install konga ./ -f values.yaml
```
#### Link

**Comment by yunsangr** [comment]
### Minikuber 부팅

```sh
> minikube delete
> minikube start
> minikube dashboard --url=true
```
> http://192.168.0.130:8001/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/#/workloads?namespace=default

**Comment by yunsangr** [comment]
### 적용 총 정리

#### Kong

```sh
> helm install my-release kong/kong 
--set ingressController.installCRDs=false 
--set admin.enabled=true                                 # kong admin 활성화
--set admin.http.enabled=true                            # kong admin http 활성화
--set admin.tls.enabled=true                             # kong admin tls 활성화
--set env.database=postgres                              # db postgresql 지정
--set env.pg_database=kong                               # psql db 이름 설정
--set env.pg_user=kong                                   # psql db 유저 이름 설정
--set pg_password=kong                                   # psql db 유저 비밀번호 설정
--set postgresql.enabled=true                            # sub charts postgresql 사용 선언
--set postgresql.postgresqlDatabase=kong                 # sub charts postgresql database 설정
--set postgresql.postgresqlUsername=kong                 # sub charts postgresql username 설정
--set postgresql.postgresqlPassword=kong                 # sub charts postgresql password 설정
```

#### Konga (UI)
```sh
> cd path/to/konga-charts
> helm install konga ./ -f
```

#### Load image into k8s
```sh
> minikube image load mdwalks_clue_api
> minikube image load mdwalks_clue_client
> minikube image list
```


#### Run CLUE project with Images
```sh
> kompose convert -f docker-compose.yml --out clue-kompose.yml
> kubectl apply -f clue-kompose.yml
```


#### Set Gateway routes with Konga
```sh
> minikube service list 
|----------------------|--------------------------------|---------------------|---------------------------|
|      NAMESPACE       |              NAME              |     TARGET PORT     |            URL            |
|----------------------|--------------------------------|---------------------|---------------------------|
| default              | konga                          | http/80             | http://192.168.49.2:30710 |
...
|----------------------|--------------------------------|---------------------|---------------------------|

```
Konga 접근 주소를 확인후 접근합니다.

접근 후 이미 동작이 확인된 snapshot.json 을 설정하거나 Konga UI 에서 원하는 서비스들의 라우트를 설정합니다.
